name: Run Django Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: ia4c_dev
          MYSQL_USER: ia4c_user
          MYSQL_PASSWORD: securepass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Copy .env.ci to .env
      run: |
        cp backend/.env.ci backend/.env
        echo "===== .env copied to .env ====="
        cat backend/.env

    - name: Export environment variables from .env
      run: |
        set -o allexport
        source backend/.env
        set +o allexport

    - name: Install mysql-client
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h "$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done
      env:
        MYSQL_HOST: db
        MYSQL_USER: ia4c_user
        MYSQL_PASSWORD: securepass

    - name: Debug MySQL connection
      run: |
        mysql -h "$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "SHOW DATABASES;"
      env:
        MYSQL_HOST: db
        MYSQL_USER: ia4c_user
        MYSQL_PASSWORD: securepass

    - name: Run migrations
      run: |
        cd backend
        python manage.py migrate
      env:
        MYSQL_HOST: db
        MYSQL_USER: ia4c_user
        MYSQL_PASSWORD: securepass

    - name: Run tests
      run: |
        cd backend
        pytest
      env:
        MYSQL_HOST: db
        MYSQL_USER: ia4c_user
        MYSQL_PASSWORD: securepass
